Bquiz.Display/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Bquiz.Display.Helpers;
using BquizDB.Entities;
using BquizDB.Business;
using Bquiz.Display.Models;

namespace Bquiz.Display.Controllers
{
    public class GroupController : Controller
    {
        #region UpdateGroup
        //Viết vào cái này nhé
        [Authorize]
        public ActionResult UpdatePart1(Guid groupId)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            //Phải là người tạo mới được sửa
            if (bl_group.GetById(groupId).bq_Quiz.UserId == ps_Membership.GetUser().UserId)
            {
                var group = bl_group.GetById(groupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);

                ps_Group part1 = new ps_Group();
                part1.Group = group;
                part1.QuestionList = questionList;

                ViewBag.QuizId = group.QuizId;
                return View(part1);
            }
            else
            {
                return Redirect("/");
            }
        }
        [HttpPost]
        public ActionResult UpdatePart1(ps_Group part1)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            bl_group.Update(
                part1.Group.QuestionGroupId,
                part1.Group.Paragraph);

            if (ModelState.IsValid)
            {
                foreach (var question in part1.QuestionList)
                {
                    bl_question.Update(
                        question.QuestionId,
                        question.Paragraph,
                        question.OptionA,
                        question.OptionB,
                        question.OptionC,
                        question.OptionD,
                        question.Answer);
                }

                part1.Group = bl_group.GetById(part1.Group.QuestionGroupId);
                ViewBag.QuizId = part1.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part1.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part1.QuestionList = questionList;

                return View(part1);
            }
            else
            {
                //Nếu như dữ liệu gởi lên không đạt yêu cầu
                //Trả về client trạng thái dữ liệu đang làm dở
                part1.Group = bl_group.GetById(part1.Group.QuestionGroupId);
                ViewBag.QuizId = part1.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part1.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part1.QuestionList = questionList;

                return View(part1);
            }
        }

        //Viết vào cái này nhé
        [Authorize]
        public ActionResult UpdatePart2(Guid groupId)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            if (bl_group.GetById(groupId).bq_Quiz.UserId == ps_Membership.GetUser().UserId)
            {
                var group = bl_group.GetById(groupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);

                ps_Group part2 = new ps_Group();
                part2.Group = group;
                part2.QuestionList = questionList;

                ViewBag.QuizId = group.QuizId;
                return View(part2);
            }
            else return Redirect("/");
        }
        [HttpPost]
        public ActionResult UpdatePart2(ps_Group part2)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            bl_group.Update(
                part2.Group.QuestionGroupId,
                part2.Group.Paragraph);

            if (ModelState.IsValid)
            {
                foreach (var question in part2.QuestionList)
                {
                    bl_question.Update(
                        question.QuestionId,
                        question.Paragraph,
                        question.OptionA,
                        question.OptionB,
                        question.OptionC,
                        question.OptionD,
                        question.Answer);
                }

                part2.Group = bl_group.GetById(part2.Group.QuestionGroupId);
                ViewBag.QuizId = part2.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part2.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part2.QuestionList = questionList;

                return View(part2);
            }
            else
            {
                //Nếu như dữ liệu gởi lên không đạt yêu cầu
                //Trả về client trạng thái dữ liệu đang làm dở
                part2.Group = bl_group.GetById(part2.Group.QuestionGroupId);
                ViewBag.QuizId = part2.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part2.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part2.QuestionList = questionList;

                return View(part2);
            }
        }

        //Viết vào cái này nhé
        [Authorize]
        public ActionResult UpdatePart3(Guid groupId)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            if (bl_group.GetById(groupId).bq_Quiz.UserId == ps_Membership.GetUser().UserId)
            {
                var group = bl_group.GetById(groupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);

                ps_Group part3 = new ps_Group();
                part3.Group = group;
                part3.QuestionList = questionList;

                //db.bq_QuestionGroup_UpdateMediaPath(groupId,null);
                ViewBag.QuestionGroupId = groupId;
                ViewBag.QuizId = group.QuizId;
                return View(part3);
            }
            else
            {
                return Redirect("/");
            }

        }
        //Xử lý từ phía Client Part3
        [HttpPost]
        public ActionResult UpdatePart3(ps_Group part3)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            if (ModelState.IsValid)
            {
                bl_group.Update(
                    part3.Group.QuestionGroupId,
                    part3.Group.Paragraph);

                foreach (var question in part3.QuestionList)
                {
                    bl_question.Update(
                        question.QuestionId,
                        question.Paragraph,
                        question.OptionA,
                        question.OptionB,
                        question.OptionC,
                        question.OptionD,
                        question.Answer);
                }

                part3.Group = bl_group.GetById(part3.Group.QuestionGroupId);
                ViewBag.QuizId = part3.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part3.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part3.QuestionList = questionList;

                //Trả về trang chủ
                return View(part3);
            }
            else
            {
                //Nếu như dữ liệu gởi lên không đạt yêu cầu
                //Trả về client trạng thái dữ liệu đang làm dở
                part3.Group = bl_group.GetById(part3.Group.QuestionGroupId);
                ViewBag.QuizId = part3.Group.QuizId;

                //chỉnh lại khi request
                var group = bl_group.GetById(part3.Group.QuestionGroupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);
                part3.QuestionList = questionList;

                return View(part3);
            }
        }

        //Update Part4
        [Authorize]
        public ActionResult UpdatePart4(Guid groupId)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            if (bl_group.GetById(groupId).bq_Quiz.UserId == ps_Membership.GetUser().UserId)
            {
                var group = bl_group.GetById(groupId);
                var questionList = bl_question.GetByGroupId(group.QuestionGroupId);

                ps_Group part4 = new ps_Group();
                part4.Group = group;
                part4.QuestionList = questionList;

                ViewBag.QuestionGroupId = groupId;
                ViewBag.QuizId = group.QuizId;
                return View(part4);
            }
            else
            {
                return Redirect("/");
            }
        }
        //Xử lý từ phía Client Part4
        [HttpPost]
        public ActionResult UpdatePart4(ps_Group part4)
        {
            bl_QuestionGroup bl_group = new bl_QuestionGroup();
            bl_Question bl_question = new bl_Question();

            if (ModelState.IsValid)
            {
                bl_group.Update(
                    part4.Group.QuestionGroupId,
                    part4.Group.Paragraph);

                foreach (var question in part4.QuestionList)
                {
                    bl_question.Update(
                        question.QuestionId,
                        question.Paragraph,

Bquiz.Display/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BquizDB.Entities;
using BquizDB.Business;
using Bquiz.Display.Helpers;
using Bquiz.Display.Models;

namespace Bquiz.Display.Controllers
{
    public class PartController : Controller
    {
        public ActionResult Index(Guid quizId)
        {
            bl_Part bl_part = new bl_Part();
            var model = bl_part.GetByParentId(0);

            ViewBag.QuizId = quizId;
            return View(model); ;
        }

        public ActionResult EdittingMenu(Guid? quizId)
        {
            if (!quizId.HasValue)
                quizId = Guid.Parse("55A0C125-226C-454D-B8D9-D70E8E75045E");

            bl_Quiz bl_quiz = new bl_Quiz();
            bl_Part bl_part = new bl_Part();

            var quiz = bl_quiz.GetById(quizId.Value);
            var parts = bl_part.GetAllChild();

            //var quiz = db.bq_Quiz_GetById(quizId).Single();
            //var parts = db.bq_Part_GetAllChilds().ToList();

            ViewBag.QuizId = quizId;
            ViewBag.QuizName = quiz.Name;

            return View(parts);
        }

        public ActionResult PublishingMenu(Guid? quizId, Guid testId)
        {
            if (!quizId.HasValue)
                quizId = Guid.Parse("55A0C125-226C-454D-B8D9-D70E8E75045E");

            bl_Quiz bl_quiz = new bl_Quiz();
            bl_Part bl_part = new bl_Part();

            var quiz = bl_quiz.GetById(quizId.Value);
            var parts = bl_part.GetAllChild();

            ViewBag.QuizId = quizId;
            ViewBag.QuizName = quiz.Name;
            ViewBag.TestId = testId;

            return View(parts);
        }

        public ActionResult PublishingMenuResult(Guid? quizId, Guid testId)
        {
            if (!quizId.HasValue)
                quizId = Guid.Parse("55A0C125-226C-454D-B8D9-D70E8E75045E");

            bl_Quiz bl_quiz = new bl_Quiz();
            bl_Part bl_part = new bl_Part();

            var quiz = bl_quiz.GetById(quizId.Value);
            var parts = bl_part.GetAllChild();

            ViewBag.QuizId = quizId;
            ViewBag.QuizName = quiz.Name;
            ViewBag.TestId = testId;

            return View(parts);
        }
    }
}

Bquiz.Display/Views/Group/AnswerBoard.cshtml
@model IEnumerable<BquizDB.Entities.bq_Answer>
@{Layout = null;}

<table class="table table-striped" style="margin-top:0px">
    <tr>
        <th>No.</th>
        <th style="text-align: center">
            <span class="label label-danger">A</span></th>
        <th style="text-align: center">
            <span class="label label-danger">B</span></th>
        <th style="text-align: center">
            <span class="label label-danger">C</span></th>
        <th style="text-align: center">
            <span class="label label-danger">D</span></th>
    </tr>

    @foreach (var answer in Model)
    {
        <tr>
            <td style="padding-left:8px">@answer.bq_Question.Order</td>

            @if (@answer.Answer == 1)
            { 
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="1"  checked="checked" /></td>
            }
            else
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="1" /></td>
            }
            @if (@answer.Answer == 2)
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="2" checked="checked" /></td>
            }
            else
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="2"  /></td>    
            }
            @if (@answer.Answer == 3)
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="3"  checked="checked" /></td> 
            }
            else
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="3"  /></td> 
            }
            @if (@answer.Answer == 4)
            { 
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="4"  checked="checked" /></td>
            }
            else
            {
                <td style="text-align: center">
                    <input type="radio" name="@answer.QuestionId" value="4"  /></td>
            }

        </tr>
        
        @Html.HiddenFor(m => answer.TestId)
    }
</table>

<script>
    //Lấy questionId hiện tại và cập nhật mới lên server
    (function () {
        $('input[type=radio]').change(function () {

            var testId = document.getElementById('answer_TestId').value;
            var questionId = this.name;

            $.ajax({
                type: 'Post',
                url: '@Url.Content("/group/updateAnswer")',
                data: 'testId=' + testId + '&questionId=' + questionId + '&answer=' + this.value,
                dataType: 'html',
                success: (function (mess) {
                    console.log(testId + ":" + questionId + ":" + mess);
                })
            });
        });
    })();
</script>

Bquiz.Display/Views/Group/Index.cshtml
@model IEnumerable<Bquiz.Models.bq_QuestionGroup>

@{
    ViewBag.Title = "Index";
}

<h2>@(((Bquiz.Models.bq_Part)ViewBag.Part).Name)</h2>

<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Order
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@item.bq_Part.EdittingUrl?groupId=@item.QuestionGroupId"><b>@item.Name</b></a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order)
        </td>
        <td>
            <a href="@item.bq_Part.EdittingUrl?groupId=@item.QuestionGroupId">TuCuong</a>
        </td>
    </tr>
}

</table>

Bquiz.Display/Views/Group/Link.cshtml
@model BquizDB.Entities.bq_Question

@{
    ViewBag.Title = "Câu hỏi được chia sẻ";
}

<div style="font-size:22px; margin-bottom:20px">
    <span class="label label-info" style="font-weight:lighter; font-family:tahoma">
        @ViewBag.DisplayName nhờ bạn trả lời câu hỏi này</span>
</div>

@Html.Partial("_QuestionView", Model)

Bquiz.Display/Views/Group/Result_Test.cshtml
@model Bquiz.Models.bq_Group
<!DOCTYPE bquiz SYSTEM "../../Content/Defined/bquiz.dtd">
@{
    ViewBag.Title = "Result_Test for Test ID ";
    Layout = null;
}


<html>
<head>
    <title>Result of Test</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>


    @(Html.Telerik().StyleSheetRegistrar().DefaultGroup(group => group.Add("telerik.common.css").Add("telerik.metro.css").Combined(true).Compress(true)))

</head>

<body>
    
    @Html.Partial("_HeaderPartial")
    <div class="page">
        <div id="Main">
            <input type="hidden" id="partordername_result" value="@String.Format("Part {0} : {1}", Model.Group.bq_Part.Order, Model.Group.bq_Part.Name)" /> @*lấy tên của part để expand menu*@
            <div>
                <div id="LeftPanel">

                    @Html.Action("PublishingMenuResult", "Part", new { quizId = ViewBag.QuizId, testId = (Guid)ViewBag.TestId })
                </div>

                <div id="MainPanel" style="height: 100%">
                    @Html.Partial("/Views/QuestionGroup/_TopTestingNav_Result.cshtml", Bquiz.BquizHelper.BquizHelpers.GetNav((Guid)ViewBag.GroupId))

                    <div>

                        <p>@Model.Group.Name</p>

                        @if (Model.Group.Paragraph != null)
                        {
                            <p>
                                @Html.Raw(Model.Group.Paragraph)
                            </p>
                        }

                        @if (Model.Group.MediaPath != null)
                        {
                            <audio controls="controls">
                                <source src="\Bquiz_Data\Audio\@Model.Group.MediaPath" type="audio/mpeg">
                                Your browser does not support the audio element.
                            </audio>
                        }
                    </div>

                    <div>
                        @foreach (var question in Model.QuestionList)
                        {
                           
                            <div class="Element">
                                <div class="ImportantElement">Question @question.Order</div>

                                @if (question.Paragraph != null)
                                {
                                    <div>
                                        @question.Paragraph
                                    </div>
                                }
                                @if (question.MediaPath != null)
                                {
                                    <audio controls="controls">
                                        <source src="\Bquiz_Data\Audio\@question.MediaPath" type="audio/mpeg">
                                        Your browser does not support the audio element.
                                    </audio>
                                }
                                @if (question.ImagePath != null)
                                {
                                    <img src="\Bquiz_Data\Images\@question.ImagePath" width="100%" />
                                }

                                <div>
                                    <table>
                                        <tr>
                                            <td style="width: 80px; vertical-align: top">
                                                @if (Bquiz.BquizHelper.BquizHelpers.GetAnswer((Guid)ViewBag.TestId, question.QuestionId).Answer == 1)
                                                {       
                                                    <img src="../../Content/images/Delete.png" width="20" />                                      
                                                     
                                                    if (question.Answer == 1)
                                                    {
                                               
                                                    <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                                else
                                                {
                                                    <img src="../../Content/images/CharacterA-Smoke.png" width="20" /> 
                                                    if (question.Answer == 1)
                                                    {
                                               
                                                    <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                            </td>
                                            <td>@question.OptionA</td>

                                        </tr>
                                        <tr>
                                            <td style="width: 80px; vertical-align: top">
                                                @if (Bquiz.BquizHelper.BquizHelpers.GetAnswer((Guid)ViewBag.TestId, question.QuestionId).Answer == 2)
                                                {
                                                    <img src="../../Content/images/Delete.png" width="20" /> 
                                                    
                                                    if (question.Answer == 2)
                                                    {
                                               
                                                    <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                                else
                                                {
                                                    <img src="../../Content/images/CharacterB-Smoke.png" width="20" />
                                                    if (question.Answer == 2)
                                                    {
                                               
                                                   <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                            </td>
                                            <td>@question.OptionB</td>
                                        </tr>
                                        <tr>
                                            <td style="width: 80px; vertical-align: top">
                                                @if (Bquiz.BquizHelper.BquizHelpers.GetAnswer((Guid)ViewBag.TestId, question.QuestionId).Answer == 3)
                                                {
                                                     <img src="../../Content/images/Delete.png" width="20" /> 
                                                    
                                                    if (question.Answer == 3)
                                                    {
                                               
                                                   <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                                else
                                                { 
                                                    <img src="../../Content/images/CharacterC-Smoke.png" width="20" />
                                                    if (question.Answer == 3)
                                                    {
                                               
                                                    <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                            </td>
                                            <td>@question.OptionC</td>
                                        </tr>
                                        <tr>
                                            <td style="width: 80px; vertical-align: top">
                                                @if (Bquiz.BquizHelper.BquizHelpers.GetAnswer((Guid)ViewBag.TestId, question.QuestionId).Answer == 4)
                                                {
                                                    <img src="../../Content/images/Delete.png" width="20" /> 
                                                    
                                                    if (question.Answer == 4)
                                                    {
                                               
                                                     <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                                else
                                                {
                                                    <img src="../../Content/images/CharacterD-Smoke.png" width="20" />
                                                    if (question.Answer == 4)
                                                    {
                                               
                                                     <img src="../../Content/images/Check Box.png" width="20" />
                                            
                                                    }
                                                }
                                            </td>
                                            <td>@question.OptionD</td>
                                        </tr>

                                    </table>
                                </div>
                            </div>
                            
                        }
                    </div>


                    @Html.Partial("/Views/QuestionGroup/_BottomTestingNav_Result.cshtml", Bquiz.BquizHelper.BquizHelpers.GetNav((Guid)ViewBag.GroupId))
                </div>
                <div id="RightPanel">
                    <ul class="nav">
                        <li style="text-align: left">Score:<br />
                            Listening=@Bquiz.BquizHelper.BquizHelpers.GetMark_Listen(@ViewBag.TestID)
                            <br />
                            Reading=@Bquiz.BquizHelper.BquizHelpers.GetMark_Read(@ViewBag.TestID) <br />
                            Total=@Bquiz.BquizHelper.BquizHelpers.GetMark(@ViewBag.TestID)
                        </li>
                        <li style="text-align: left">Right:@Bquiz.BquizHelper.BquizHelpers.GetRight(@ViewBag.TestID)  </li>
                        <li style="text-align: left">Done: @ViewBag.QuestionDone /200</li>
                        <li style="text-align: left">Your Choice:
                            <img src="../../Content/images/Delete.png" width="40" /></li>
                        <li style="text-align: left">Answer:
                            <img src="../../Content/images/Check Box.png" width="40" /></li>
                    </ul>

                </div>
            </div>
        </div>
    </div>
    @(Html.Telerik().ScriptRegistrar().DefaultGroup(group => group.Combined(true).Compress(true)))
</body>
</html>

Bquiz.Display/Views/Group/Share.cshtml
@model Bquiz.Display.Models.ps_Group

@{
    ViewBag.Title = "Nhóm câu hỏi được chia sẻ";
}

<div style="font-size:22px; margin-bottom:20px">
    <span class="label label-info" style="font-weight:lighter; font-family:tahoma">
        @ViewBag.DisplayName nhờ bạn trả lời nhóm câu hỏi này</span>
</div>

<div>
    @if (Model.Group.Paragraph != null)
    {
        <p>
            @Html.Raw(Model.Group.Paragraph)
        </p>
    }

    @if (Model.Group.MediaPath != null)
    {
        <audio controls="controls">
            <source src="\Bquiz_Data\Audio\@Model.Group.MediaPath" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
    }
</div>

<div style="padding-bottom:20px">
    @foreach (var question in Model.QuestionList)
    {   
        @Html.Partial("_QuestionView", question)
    }
</div>

Bquiz.Display/Views/Group/_BottomEditNav.cshtml
@model Bquiz.Models.bq_TestingNav

<div>
    <p style="float:right;">
        @if(Model.PreGroup != null)
        {
            <a href="/questiongroup/view?groupId=@Model.PreGroup&testId=@ViewBag.TestId" class="DarkMetroButton" style="width:50px;">
                <img src="../../Content/images/Swap%20Left.png" width="20" style="margin-top:-5px; margin-bottom:-5px"/>
            </a>
        }

        @if(Model.NextGroup!=null)
        {
            <a href="/questiongroup/view?groupId=@Model.NextGroup&testId=@ViewBag.TestId" class="DarkMetroButton" style="width:120px;">
                Next
                <img src="../../Content/images/ArrowHead-Right.png" width="10" />
            </a>
        }
    </p>
                        
</div>

Bquiz.Display/Views/Group/_BottomTestingNav.cshtml
@model Bquiz.Models.bq_TestingNav

<div>
    <p style="float:right;">
        @if(Model.PreGroup != null)
        {
            <a href="/questiongroup/view?groupId=@Model.PreGroup&testId=@ViewBag.TestId" class="DarkMetroButton" style="width:50px;" >
                <img src="../../Content/images/Swap%20Left.png" width="20" style="margin-top:-5px; margin-bottom:-5px"/>
            </a>
        }

        @if(Model.NextGroup!=null)
        {
            <a href="/questiongroup/view?groupId=@Model.NextGroup&testId=@ViewBag.TestId" class="DarkMetroButton" style="width:120px;">
                Next
                <img src="../../Content/images/ArrowHead-Right.png" width="10" />
            </a>
        }
    </p>
                        
</div>

Bquiz.Display/Views/Group/_NavigationItem.cshtml
@model Bquiz.Display.Models.ps_PartViewItem

<div class="btn-group">
    <button class="btn-bquiz btn btn-link" data-toggle="dropdown">
        @Model.PartName</button>

    <ul class="dropdown-menu" role="menu">
        @foreach(var item in Model.Groups)
        {
        <li>
            <a href="@Url.Action("Run", "Group", 
                new { testId=Model.TestId, groupId=item.QuestionGroupId })">
                @item.Name

                <span class="label label-success pull-right">
                    <span class="glyphicon glyphicon-ok"></span>
                </span>
            </a></li>
        }
    </ul>
</div>